name: Pull Request Docs Check
on: pull_request

jobs:
  documentation-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upgrade pip
        run: "python -m pip install --upgrade pip"
      - name: Install dependencies [sinergym extras]
        run: "pip install -e .[extras]"
      - name: Compile documentation
        run: "cd docs && sphinx-build -M html source build -W"

