name: Pull Request Docs Check
on: pull_request

jobs:
  documentation-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify documentation update
        uses: dorny/paths-filter@v2
        id: verify-documentation-update
        with:
          filters: |
            doc:
              - 'docs/source/**'

      - name: Upgrade pip
        if: steps.verify-documentation-update.outputs.doc == 'true'
        run: "python -m pip install --upgrade pip"
      - name: Install dependencies [sinergym extras]
        if: steps.verify-documentation-update.outputs.doc == 'true'
        run: "pip install -e .[extras]"
      - name: Compile documentation
        if: steps.verify-documentation-update.outputs.doc == 'true'
        run: "cd docs && sphinx-build -M html source build -W"

