name: Python code format (autopep8)
on: pull_request

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - name: Copy code
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: autopep8 check and fix
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .

      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated autopep8 fixes
